Repository Team-MindWay/Mindway-v2-Android, pull requests merged in 2024-10, with the labels that each got.

#449 🔀 :: (#448) - change swiperefreshindicator content color
  presentation/src/main/java/com/chobo/presentation/view/book/screen/BookScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/event/screen/EventScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/main/screen/GoalReadingScreen.kt
Labels: 2️⃣ Priortiy: Mediuminvalid, ⚡Type: Simple

#451 🔀 :: (#450) - Chuck 라이브러리를 적용하여 REST API 통신이 정상적으로 되는지 앱 안에서 확인이 가능하도록 했습니다.
  app/build.gradle.kts
  app/src/main/java/com/chobo/mindway_v2_android/module/NetworkModule.kt
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/ProjectProperties.kt
  buildSrc/src/main/kotlin/Versions.kt
  gradle.properties
Labels: 2️⃣ Priortiy: Mediuminvalid, ✨ Type: Feature

#452 Update README.md
  README.md
Labels: 3️⃣ Priority: Low, 📄 Type: Docs

#454 🔀 :: (#453) - use graphviz dependency graph
  build.gradle.kts
  gradle.properties
  gradle/projectDependencyGraph.gradle
  project.dot.png
Labels: 2️⃣ Priortiy: Mediuminvalid, ✨ Type: Feature

#456 🔀 :: (#445) - Refactor Dummy Interceptor
  app/src/main/java/com/chobo/mindway_v2_android/module/NetworkModule.kt
Labels: 1️⃣ Priority: High, 🔨 Type: Refector

#458 🔀 :: (#457) - Refactor Text Value
  presentation/src/main/java/com/chobo/presentation/view/main/screen/HomeScreen.kt
Labels: 🔨 Type: Refector

#460 🔀 :: (#459) - modify app data build gradle file
  app/build.gradle.kts
  data/build.gradle.kts
Labels: 0️⃣ Priority: Critical, 🔨 Type: Refector

#462 🔀 :: (#461) - Add SwipeRefreshLoading Code -> StateFlow
  presentation/src/main/java/com/chobo/presentation/view/event/screen/EventScreen.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/event/EventViewModel.kt
Labels: 0️⃣ Priority: Critical, 🐞 Type: Bug

#464 🔀 :: (#463) - changed targetsdk version upgrade
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/chobo/mindway_v2_android/module/NetworkModule.kt
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: 0️⃣ Priority: Critical

#466 🔀 :: (#465) - Fix Bug assembleDevDebug -> Changed build.gradle.kts(:app)
  app/build.gradle.kts
Labels: 0️⃣ Priority: Critical, 🐞 Type: Bug

#469 🔀 :: (#467) - Gauth Version Update
  buildSrc/src/main/kotlin/Versions.kt
Labels: 0️⃣ Priority: Critical

#475 🔀 :: (#474) - suspend 함수가 필요 없는 부분을 일반 함수로 바꾸었습니다.
  data/src/main/java/com/chobo/data/remote/datasource/auth/RemoteAuthDataSource.kt
  data/src/main/java/com/chobo/data/remote/datasource/auth/RemoteAuthDataSourceImpl.kt
  data/src/main/java/com/chobo/data/remote/datasource/book/RemoteBookDataSource.kt
  data/src/main/java/com/chobo/data/remote/datasource/book/RemoteBookDataSourceImpl.kt
  data/src/main/java/com/chobo/data/remote/datasource/event/RemoteEventDataSource.kt
  data/src/main/java/com/chobo/data/remote/datasource/event/RemoteEventDataSourceImpl.kt
  data/src/main/java/com/chobo/data/remote/datasource/goal/RemoteGoalDataSource.kt
  data/src/main/java/com/chobo/data/remote/datasource/goal/RemoteGoalDataSourceImpl.kt
  data/src/main/java/com/chobo/data/remote/datasource/my/RemoteMyDataSource.kt
  data/src/main/java/com/chobo/data/remote/datasource/my/RemoteMyDataSourceImpl.kt
  data/src/main/java/com/chobo/data/remote/datasource/notice/RemoteNoticeDataSource.kt
  data/src/main/java/com/chobo/data/remote/datasource/notice/RemoteNoticeDataSourceImpl.kt
  data/src/main/java/com/chobo/data/remote/datasource/order/RemoteOrderDataSource.kt
  data/src/main/java/com/chobo/data/remote/datasource/order/RemoteOrderDataSourceImpl.kt
  data/src/main/java/com/chobo/data/remote/datasource/rank/RemoteRankDataSource.kt
  data/src/main/java/com/chobo/data/remote/datasource/rank/RemoteRankDataSourceImpl.kt
  data/src/main/java/com/chobo/data/remote/datasource/recommend/RemoteRecommendDataSource.kt
  data/src/main/java/com/chobo/data/remote/datasource/recommend/RemoteRecommendDataSourceImpl.kt
  data/src/main/java/com/chobo/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/chobo/data/repository/BookRepositoryImpl.kt
  data/src/main/java/com/chobo/data/repository/EventRepositoryImpl.kt
  data/src/main/java/com/chobo/data/repository/GoalRepositoryImpl.kt
  data/src/main/java/com/chobo/data/repository/MyRepositoryImpl.kt
  data/src/main/java/com/chobo/data/repository/NoticeRepositoryImpl.kt
  data/src/main/java/com/chobo/data/repository/OrderRepositoryImpl.kt
  data/src/main/java/com/chobo/data/repository/RankRepositoryImpl.kt
  data/src/main/java/com/chobo/data/repository/RecommendRepositoryImpl.kt
  domain/src/main/java/com/chobo/domain/repository/AuthRepository.kt
  domain/src/main/java/com/chobo/domain/repository/BookRepository.kt
  domain/src/main/java/com/chobo/domain/repository/EventRepository.kt
  domain/src/main/java/com/chobo/domain/repository/GoalRepository.kt
  domain/src/main/java/com/chobo/domain/repository/MyRepository.kt
  domain/src/main/java/com/chobo/domain/repository/NoticeRepository.kt
  domain/src/main/java/com/chobo/domain/repository/OrderRepository.kt
  domain/src/main/java/com/chobo/domain/repository/RankRepository.kt
  domain/src/main/java/com/chobo/domain/repository/RecommendRepository.kt
  domain/src/main/java/com/chobo/domain/usecase/auth/GAuthLoginUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/auth/LogoutUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/auth/TokenRefreshUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/book/BookDeleteByIdUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/book/BookModifyUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/book/BookUploadUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/book/GetBookByIdUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/book/GetBookListUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/event/GetDetailEventUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/event/GetEventListUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/goal/GetWeekendGoalUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/goal/PostGoalRequestUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/my/GetMyBookListUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/my/GetMyInformationUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/notice/NoticeGetUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/order/OrderDeleteByIdUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/order/OrderModifyByIdUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/order/OrderUploadUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/rank/GetRankUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/recommend/DeleteRecommendBookUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/recommend/GetRecommendBookUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/recommend/PatchRecommendBookUseCase.kt
  domain/src/main/java/com/chobo/domain/usecase/recommend/PostRecommendBookUseCase.kt
Labels: 2️⃣ Priortiy: Mediuminvalid, 🔨 Type: Refector
