Repository Team-MindWay/Mindway-v2-Android, pull requests merged in 2024-04, with the labels that each got.

#11 :twisted_rightwards_arrows: :: (#6) - add mindway design guide
  .idea/misc.xml
  app/build.gradle.kts
  buildSrc/src/main/kotlin/Versions.kt
  data/src/main/java/com/chobo/data/.gitkeep
  domain/src/main/java/com/chobo/domain/.gitkeep
  presentation/build.gradle.kts
  presentation/src/main/java/com/chobo/presentation/view/component/button/MindWayButton.kt
  presentation/src/main/java/com/chobo/presentation/view/component/customToast/MindWayToast.kt
  presentation/src/main/java/com/chobo/presentation/view/component/icon/MindWayIcon.kt
  presentation/src/main/java/com/chobo/presentation/view/component/textField/MindWayTextField.kt
  presentation/src/main/java/com/chobo/presentation/view/screen/.gitkeep
  presentation/src/main/java/com/chobo/presentation/view/theme/MindWayTypography.kt
  presentation/src/main/java/com/chobo/presentation/view/theme/Theme.kt
  presentation/src/main/java/com/chobo/presentation/view/theme/color/ColorTheme.kt
  presentation/src/main/java/com/chobo/presentation/view/theme/color/MindWayColor.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/.gitkeep
  presentation/src/main/res/drawable/ic_book.xml
  presentation/src/main/res/drawable/ic_book_selected.xml
  presentation/src/main/res/drawable/ic_chevron_down.xml
  presentation/src/main/res/drawable/ic_chevron_left.xml
  presentation/src/main/res/drawable/ic_chevron_right.xml
  presentation/src/main/res/drawable/ic_chevron_top.xml
  presentation/src/main/res/drawable/ic_edit.xml
  presentation/src/main/res/drawable/ic_fail.xml
  presentation/src/main/res/drawable/ic_heart.xml
  presentation/src/main/res/drawable/ic_heart_selected.xml
  presentation/src/main/res/drawable/ic_home.xml
  presentation/src/main/res/drawable/ic_home_selected.xml
  presentation/src/main/res/drawable/ic_info.xml
  presentation/src/main/res/drawable/ic_mindway.xml
  presentation/src/main/res/drawable/ic_option.xml
  presentation/src/main/res/drawable/ic_plus.xml
  presentation/src/main/res/drawable/ic_profile.xml
  presentation/src/main/res/drawable/ic_profile_selected.xml
  presentation/src/main/res/drawable/ic_success.xml
  presentation/src/main/res/drawable/ic_trash_can.xml
  presentation/src/main/res/font/pretendard_regular.ttf
  presentation/src/main/res/font/pretendard_semi_bold.ttf
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing, ⚙ Type: Setting

#16 :twisted_rightwards_arrows: :: (#14) - compose navigation setting
  app/src/main/java/com/chobo/mindway_v2_android/MindWayNavHost.kt
  app/src/main/java/com/chobo/mindway_v2_android/Module/.gitkeep
Labels: 2️⃣ Priortiy: Mediuminvalid, ✨ Type: Feature

#21 🔀 :: (#20) Replacing_String_Literals_with_Variables_in_a_Project
  presentation/src/main/res/values/strings.xml
Labels: 3️⃣ Priority: Low, ⚙ Type: Setting

#25 🔀 :: (#15) main_goal_reading_component_publishing
  presentation/src/main/java/com/chobo/presentation/view/component/textField/MindWayTextField.kt
  presentation/src/main/java/com/chobo/presentation/view/component/topBar/MindWayTopBar.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingBottomSheet.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingChart.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingGraph.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingIndicator.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingListOfBooksReadItem.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingPlusCard.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/HomeGoalReadingChart.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/HomeNoticeCard.kt
  presentation/src/main/res/values/strings.xml
Labels: 2️⃣ Priortiy: Mediuminvalid, 🎨 Type: Publishing

#26 🔀 :: (#18) details_view_component_publishing
  presentation/src/main/java/com/chobo/presentation/view/main/component/ViewDetailTextCard.kt
Labels: 2️⃣ Priortiy: Mediuminvalid, 🎨 Type: Publishing

#32 🔀 :: (#29) - add_preview
  presentation/src/main/java/com/chobo/presentation/view/component/button/MindWayButton.kt
  presentation/src/main/java/com/chobo/presentation/view/component/customToast/MindWayToast.kt
  presentation/src/main/java/com/chobo/presentation/view/component/textField/MindWayTextField.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingBottomSheet.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingGraph.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingIndicator.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingListOfBooksReadItem.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/HomeGoalReadingChart.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/HomeNoticeCard.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/HomeReadersOfTheMonthChart.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/HomeReadersOfTheMonthGraph.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature, ⚡Type: Simple

#37 🔀 :: (#33) - icon_modify
  presentation/src/main/java/com/chobo/presentation/view/component/icon/MindWayIcon.kt
  presentation/src/main/res/drawable/ic_book_selected.xml
  presentation/src/main/res/drawable/ic_heart_selected.xml
  presentation/src/main/res/drawable/ic_home_selected.xml
  presentation/src/main/res/drawable/ic_profile_selected.xml
  presentation/src/main/res/drawable/image_book.xml
Labels: 3️⃣ Priority: Low, 🔨 Type: Refector, ⚡Type: Simple

#39 🔀 :: (#38) - home_combination
  presentation/src/main/java/com/chobo/presentation/view/main/component/HomeNoticeCard.kt
  presentation/src/main/java/com/chobo/presentation/view/main/screen/.gitkeep
  presentation/src/main/java/com/chobo/presentation/view/main/screen/HomeScreen.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing, ⚡Type: Simple

#41 🔀 :: (#38) - goal_reading_combination
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingChart.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingListOfBooksReadItem.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingPlusCard.kt
  presentation/src/main/java/com/chobo/presentation/view/main/screen/GoalReadingScreen.kt
Labels: 2️⃣ Priortiy: Mediuminvalid, 🎨 Type: Publishing, ⚡Type: Simple

#45 🔀 :: (#43) - top_app_bar_combination
  presentation/src/main/java/com/chobo/presentation/view/book/component/.gitkeep
  presentation/src/main/java/com/chobo/presentation/view/book/component/BookRequestTopAppBar.kt
  presentation/src/main/java/com/chobo/presentation/view/component/topBar/MindWayTopBar.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/AddBookTopAppBar.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/DetailViewTopAppBar.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingTopAppBar.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/HomeTopAppBar.kt
  presentation/src/main/java/com/chobo/presentation/view/my/component/.gitkeep
  presentation/src/main/java/com/chobo/presentation/view/my/component/BookModifyTopAppBar.kt
  presentation/src/main/res/values/strings.xml
Labels: 2️⃣ Priortiy: Mediuminvalid, 🎨 Type: Publishing, ⚡Type: Simple

#52 🔀 :: (#51) - view_detail_screen_publishing
  presentation/src/main/java/com/chobo/presentation/view/main/component/ViewDetailTextCard.kt
  presentation/src/main/java/com/chobo/presentation/view/main/screen/GoalReadingScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/main/screen/HomeScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/main/screen/ViewDetailScreen.kt
Labels: 2️⃣ Priortiy: Mediuminvalid, 🎨 Type: Publishing, ⚡Type: Simple

#54 (#53) - my_component_publishing
  presentation/src/main/java/com/chobo/presentation/view/component/button/MindWayButton.kt
  presentation/src/main/java/com/chobo/presentation/view/my/component/MyBookDeletePopUp.kt
  presentation/src/main/java/com/chobo/presentation/view/my/component/MyBookListItem.kt
  presentation/src/main/java/com/chobo/presentation/view/my/component/MyBottomSheet.kt
  presentation/src/main/java/com/chobo/presentation/view/my/component/MyNameCard.kt
  presentation/src/main/res/values/strings.xml
Labels: 3️⃣ Priority: Low, 🎨 Type: Publishing

#56 🔀 :: (#55) - book_component_publishing
  presentation/src/main/java/com/chobo/presentation/view/book/component/BookListItem.kt
  presentation/src/main/java/com/chobo/presentation/view/book/component/BookPopUp.kt
Labels: 2️⃣ Priortiy: Mediuminvalid, 🎨 Type: Publishing

#58 🔀 :: (#57) - my_screen_publishing
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingChart.kt
  presentation/src/main/java/com/chobo/presentation/view/main/screen/GoalReadingScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/my/component/MyBookListItem.kt
  presentation/src/main/java/com/chobo/presentation/view/my/screen/.gitkeep
  presentation/src/main/java/com/chobo/presentation/view/my/screen/MyScreen.kt
Labels: 3️⃣ Priority: Low, 🎨 Type: Publishing

#60 🔀 :: (#59) - book_edit_screen_publishing
  presentation/src/main/java/com/chobo/presentation/view/my/screen/MyBookEditScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: 3️⃣ Priority: Low, 🎨 Type: Publishing, ⚡Type: Simple

#63 Feature/61 mindway intro screen publishing
  presentation/src/main/java/com/chobo/presentation/view/my/screen/MindWayIntroScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: 3️⃣ Priority: Low, 🎨 Type: Publishing

#69 :twisted_rightwards_arrows: :: (#68) - BottomNavigationBar_Code_Refector
  presentation/src/main/java/com/chobo/presentation/view/component/bottom_navigation_bar/MindWayNavBar.kt
  presentation/src/main/java/com/chobo/presentation/view/component/bottom_navigation_bar/MindWayNavBarItem.kt
Labels: 🔨 Type: Refector

#70 🔀 :: (#64) - book_list_screen_publishing
  presentation/src/main/java/com/chobo/presentation/view/book/component/BookTabRowItem.kt
  presentation/src/main/java/com/chobo/presentation/view/book/screen/.gitkeep
  presentation/src/main/java/com/chobo/presentation/view/book/screen/BookScreen.kt
Labels: 3️⃣ Priority: Low, 🎨 Type: Publishing

#73 :twisted_rightwards_arrows: :: (#71) - publishing_check_out_books_screen
  presentation/src/main/java/com/chobo/presentation/view/book/screen/CheckOutBookScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/component/bottom_navigation_bar/MindWayNavBar.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#74 🔀 :: (#72) - main_composable_refector
  presentation/src/main/java/com/chobo/presentation/view/book/screen/BookScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingListOfBooksReadItem.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingPlusCard.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/HomeGoalReadingChart.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/HomeNoticeCard.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/ViewDetailTextCard.kt
  presentation/src/main/java/com/chobo/presentation/view/main/navigation/HomeNavigation.kt
  presentation/src/main/java/com/chobo/presentation/view/main/screen/AddBookScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/main/screen/HomeScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/main/screen/ViewDetailScreen.kt
Labels: 3️⃣ Priority: Low, 🎨 Type: Publishing, 🔨 Type: Refector

#77 🔀 :: (#75) - add_home_viewmodel
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/chobo/presentation/view/book/screen/CheckOutBookScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/component/bottom_navigation_bar/MindWayNavBar.kt
  presentation/src/main/java/com/chobo/presentation/view/component/textField/MindWayTextField.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingBottomSheet.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/HomeReadersOfTheMonthGraph.kt
  presentation/src/main/java/com/chobo/presentation/view/main/navigation/HomeNavigation.kt
  presentation/src/main/java/com/chobo/presentation/view/main/screen/AddBookScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/main/screen/GoalReadingScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/main/screen/HomeScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/main/screen/ViewDetailScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/my/screen/MyBookEditScreen.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/.gitkeep
  presentation/src/main/java/com/chobo/presentation/viewModel/AddBookViewModel.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/GoalReadingViewModel.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/HomeViewModel.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/ViewDetailViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature, 🔨 Type: Refector

#83 :twisted_rightwards_arrows: :: (#81) - add_bottomnavigationbar_to_each_screen
  presentation/src/main/java/com/chobo/presentation/view/book/component/BookListItem.kt
  presentation/src/main/java/com/chobo/presentation/view/book/screen/BookScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/event/component/Events.kt
  presentation/src/main/java/com/chobo/presentation/view/my/screen/MyScreen.kt
Labels: ⚡Type: Simple

#84 🔀 :: (#82) - add_my_viewmodel
  app/src/main/java/com/chobo/mindway_v2_android/Module/.gitkeep
  presentation/src/main/java/com/chobo/presentation/view/book/screen/BookScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/book/screen/CheckOutBookScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/component/textField/MindWayTextField.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/BookScreenViewModel.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/CheckOutBookViewModel.kt
Labels: 3️⃣ Priority: Low, ✨ Type: Feature

#88 🔀 :: (#86) - add_my_viewmodel
  presentation/src/main/java/com/chobo/presentation/view/my/screen/MyBookEditScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/my/screen/MyScreen.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/MyBookEditViewModel.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/MyViewModel.kt
Labels: 3️⃣ Priority: Low, ✨ Type: Feature

#91 🔀 :: (#86) - add_my_viewmodel
  presentation/src/main/java/com/chobo/presentation/view/event/component/EventContent.kt
  presentation/src/main/java/com/chobo/presentation/view/event/component/EventPager.kt
  presentation/src/main/java/com/chobo/presentation/view/event/component/Events.kt
  presentation/src/main/java/com/chobo/presentation/view/event/screen/DetailEventScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/event/screen/EventScreen.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/DetailEventViewModel.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/EventViewModel.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/MyViewModel.kt
Labels: 3️⃣ Priority: Low, ✨ Type: Feature, ⚡Type: Simple

#95 :twisted_rightwards_arrows: :: fire_unused_import
  presentation/src/main/java/com/chobo/presentation/view/component/button/MindWayButton.kt
  presentation/src/main/java/com/chobo/presentation/view/component/textField/MindWayTextField.kt
  presentation/src/main/java/com/chobo/presentation/view/event/navigation/DetailEventNavigation.kt
  presentation/src/main/java/com/chobo/presentation/view/event/screen/EventScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingBottomSheet.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/HomeReadersOfTheMonthChart.kt
  presentation/src/main/java/com/chobo/presentation/view/my/screen/MyScreen.kt
Labels: 🔨 Type: Refector, ⚡Type: Simple

#97 🔀 :: (#96) - add_screen_navgraph
  app/src/main/java/com/chobo/mindway_v2_android/MindWayNavHost.kt
  presentation/src/main/java/com/chobo/presentation/view/book/navigation/.gitkeep
  presentation/src/main/java/com/chobo/presentation/view/book/navigation/BookNavigation.kt
  presentation/src/main/java/com/chobo/presentation/view/book/screen/BookAddBookScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/book/screen/BookScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/event/navigation/DetailEventNavigation.kt
  presentation/src/main/java/com/chobo/presentation/view/event/navigation/EventNavigation.kt
  presentation/src/main/java/com/chobo/presentation/view/event/screen/EventScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/main/navigation/HomeNavigation.kt
  presentation/src/main/java/com/chobo/presentation/view/main/navigation/MainNavigation.kt
  presentation/src/main/java/com/chobo/presentation/view/main/screen/GoalReadingScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/main/screen/HomeAddBookScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/main/screen/HomeScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/main/screen/ViewDetailScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/my/navigation/.gitkeep
  presentation/src/main/java/com/chobo/presentation/view/my/navigation/MyNavigation.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/BookAddBookViewModel.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/HomeAddBookViewModel.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/HomeViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature, ⚡Type: Simple

#107 :twisted_rightwards_arrows: :: (#106) - Publishing_MindWay_Gauth_SignIn_Button
  presentation/src/main/java/com/chobo/presentation/view/component/button/MindWayButton.kt
  presentation/src/main/java/com/chobo/presentation/view/login/component/GAuthButton.kt
  presentation/src/main/java/com/chobo/presentation/view/login/screen/LoginScreen.kt
  presentation/src/main/res/drawable/ic_mindway_gauth.xml
  presentation/src/main/res/drawable/ic_mindway_gauth_string.xml
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing, ⚡Type: Simple

#105 :twisted_rightwards_arrows: :: Refactor_Code
  presentation/src/main/java/com/chobo/presentation/view/book/component/BookPopUp.kt
  presentation/src/main/java/com/chobo/presentation/view/book/component/BookRequestTopAppBar.kt
  presentation/src/main/java/com/chobo/presentation/view/book/screen/BookAddBookScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/component/button/MindWayButton.kt
  presentation/src/main/java/com/chobo/presentation/view/component/customToast/MindWayToast.kt
  presentation/src/main/java/com/chobo/presentation/view/component/textField/MindWayTextField.kt
  presentation/src/main/java/com/chobo/presentation/view/component/topBar/MindWayTopBar.kt
  presentation/src/main/java/com/chobo/presentation/view/event/component/DetailEventTopBar.kt
  presentation/src/main/java/com/chobo/presentation/view/event/component/EventContent.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/AddBookTopAppBar.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/DetailViewTopAppBar.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingChart.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/GoalReadingTopAppBar.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/HomeGoalReadingChart.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/HomeTopAppBar.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/ViewDetailTextCard.kt
  presentation/src/main/java/com/chobo/presentation/view/my/component/BookModifyTopAppBar.kt
  presentation/src/main/java/com/chobo/presentation/view/my/component/MyBookDeletePopUp.kt
  presentation/src/main/java/com/chobo/presentation/view/my/component/MyBookListItem.kt
  presentation/src/main/java/com/chobo/presentation/view/my/component/MyBottomSheet.kt
  presentation/src/main/java/com/chobo/presentation/view/my/component/MyNameCard.kt
  presentation/src/main/java/com/chobo/presentation/view/my/screen/MindWayIntroScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/my/screen/MyBookEditScreen.kt
Labels: 1️⃣ Priority: High, 🔨 Type: Refector, ⚡Type: Simple

#113 🔀 :: (#110) - navigation_not_work
  app/src/main/java/com/chobo/mindway_v2_android/MindWayNavHost.kt
  presentation/src/main/java/com/chobo/presentation/view/book/navigation/BookNavigation.kt
  presentation/src/main/java/com/chobo/presentation/view/book/screen/BookScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/component/bottom_navigation_bar/MindWayNavBar.kt
  presentation/src/main/java/com/chobo/presentation/view/component/compostionView/CompostionViewNavigation.kt
  presentation/src/main/java/com/chobo/presentation/view/component/compostionView/MindWayCombinationView.kt
  presentation/src/main/java/com/chobo/presentation/view/component/scaffold/MindWayScaffold.kt
  presentation/src/main/java/com/chobo/presentation/view/main/navigation/MainNavigation.kt
  presentation/src/main/java/com/chobo/presentation/view/my/navigation/MyNavigation.kt
  presentation/src/main/java/com/chobo/presentation/view/my/screen/MyScreen.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature, 🪛 Type: Performance, 🔨 Type: Refector

#120 🔀 :: (#119) - delete_button_feedback
  presentation/src/main/java/com/chobo/presentation/view/book/component/BookListItem.kt
  presentation/src/main/java/com/chobo/presentation/view/book/component/BookTabRowItem.kt
  presentation/src/main/java/com/chobo/presentation/view/book/screen/BookScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/component/button/MindWayButton.kt
Labels: 2️⃣ Priortiy: Mediuminvalid, 🎨 Type: Publishing

#117 :twisted_rightwards_arrows: :: (#115) - add_BuildConfig
  .github/workflows/android.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/chobo/mindway_v2_android/Module/NetworkModule.kt
  data/build.gradle.kts
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#127 :twisted_rightwards_arrows: :: (#124) - Add_Pop_Up_Dialog
  presentation/src/main/java/com/chobo/presentation/view/book/component/BookPopUp.kt
  presentation/src/main/java/com/chobo/presentation/view/book/screen/BookAddBookScreen.kt
Labels: 0️⃣ Priority: Critical

#130 🔀 :: (#129) - MockData를_init으로_주입합니다
  presentation/src/main/java/com/chobo/presentation/viewModel/BookScreenViewModel.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/DetailEventViewModel.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/EventViewModel.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/GoalReadingViewModel.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/HomeViewModel.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/MyBookEditViewModel.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/MyViewModel.kt
Labels: 3️⃣ Priority: Low, ⚡Type: Simple

#147 :twisted_rightwards_arrows: ::(#128) - PopUp_Dialog
  presentation/src/main/java/com/chobo/presentation/view/book/component/BookListItem.kt
  presentation/src/main/java/com/chobo/presentation/view/book/screen/BookScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/my/component/MyBookDeletePopUp.kt
  presentation/src/main/java/com/chobo/presentation/view/my/component/MyBookListItem.kt
  presentation/src/main/java/com/chobo/presentation/view/my/screen/MyScreen.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/MyViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature, 🔨 Type: Refector

#149 :twisted_rightwards_arrows: :: (#148) - Add_MindWayListSpacer
  presentation/src/main/java/com/chobo/presentation/view/book/screen/BookScreen.kt
  presentation/src/main/java/com/chobo/presentation/view/component/spacer/MindWayListHeightSpacer.kt
Labels: 3️⃣ Priority: Low

#154 🔀 :: (#152) - home_screen_performance_improve
  presentation/src/main/java/com/chobo/presentation/view/main/component/HomeGoalReadingChart.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/HomeNoticeCard.kt
  presentation/src/main/java/com/chobo/presentation/view/main/component/HomeReadersOfTheMonthChart.kt
  presentation/src/main/java/com/chobo/presentation/view/main/screen/HomeScreen.kt
  presentation/src/main/java/com/chobo/presentation/viewModel/HomeViewModel.kt
Labels: 🪛 Type: Performance, 🎨 Type: Publishing, 🔨 Type: Refector

#162 :twisted_rightwards_arrows: :: (#160) - auth, my_ dto, api를_구현했습니다!
  data/src/main/java/com/chobo/data/remote/api/AuthAPI.kt
  data/src/main/java/com/chobo/data/remote/api/MyAPI.kt
  data/src/main/java/com/chobo/data/remote/dto/auth/request/GAuthPostRequestBody.kt
  data/src/main/java/com/chobo/data/remote/dto/auth/response/GAuthResponse.kt
  data/src/main/java/com/chobo/data/remote/dto/my_response/MyResponse.kt
Labels: 1️⃣ Priority: High, 📬 Type: API, ✨ Type: Feature

#174 :twisted_rightwards_arrows: :: (#164) - Add authinterceptor, DataSource, Module And ...
  app/build.gradle.kts
  app/src/main/java/com/chobo/mindway_v2_android/Module/DataStoreModule.kt
  app/src/main/java/com/chobo/mindway_v2_android/Module/LocalDataSourceModule.kt
  data/src/main/java/com/chobo/data/.gitkeep
  data/src/main/java/com/chobo/data/local/datasource/LocalAuthDataSource.kt
  data/src/main/java/com/chobo/data/local/datasource/LocalAuthDataSourceImpl.kt
  data/src/main/java/com/chobo/data/local/key/AuthDataStoreKey.kt
  data/src/main/java/com/chobo/data/util/AuthInterceptor.kt
  data/src/main/java/com/chobo/data/util/DataFormatter.kt
  domain/src/main/java/com/chobo/domain/.giiKeep
  presentation/src/main/java/com/chobo/presentation/view/util/errorHandling.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#181 :twisted_rightwards_arrows: :: (#176) - Organize_NetworkModule, API, DTO
  data/src/main/java/com/chobo/data/remote/api/BookAPI.kt
  data/src/main/java/com/chobo/data/remote/api/NoticeAPI.kt
  data/src/main/java/com/chobo/data/remote/dto/book/response/BookListResponse.kt
  data/src/main/java/com/chobo/data/remote/dto/book/response/BookResponse.kt
  data/src/main/java/com/chobo/data/remote/dto/notice/NoticeAll.kt
  settings.gradle.kts
Labels: 0️⃣ Priority: Critical
